console.log("Reverse :");
var Orginalnum = [1,2,3,4,5];
console.log("Original Array: ",Orginalnum);
var length = Orginalnum.length;
console.log("Length of orginal Array: ", length);
Orginalnum.reverse();
console.log("Method: Orginalnum.reverse()", "its used to reverse the order of array");
console.log("change in  Array: ", Orginalnum);
var Lengthafterreverse= Orginalnum.length;
console.log("Change in Length of orginal Array after reverse(): ", Lengthafterreverse);